version = 1

test_patterns = ["**/*.test.{js,jsx,ts,tsx}"]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "jest",
    "browser",
    "cypress"
  ]

[[transformers]]
name = "prettier"