version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "jest",
    "browser",
    "cypress"
  ]

[[transformers]]
name = "prettier"